import fs from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();

const CONFIG_PATH = path.join(ROOT, "spotify-playlists.json");
const CURRENT_PATH = path.join(ROOT, "spotify-current.json");

const CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const REFRESH_TOKEN = process.env.SPOTIFY_REFRESH_TOKEN;

if (!CLIENT_ID || !REFRESH_TOKEN) {
  console.log(
    "Spotify secrets are not configured; skipping Spotify playlist sync."
  );
  process.exit(0);
}

const API = "https://api.spotify.com/v1";
const TOKEN_URL = "https://accounts.spotify.com/api/token";

async function readJson(file, fallback = undefined) {
  try {
    return JSON.parse(await fs.readFile(file, "utf8"));
  } catch (error) {
    if (fallback !== undefined) {
      return fallback;
    }

    throw new Error(
      `Required JSON file could not be read: ${file}: ${error.message}`
    );
  }
}

async function refreshAccessToken() {
  const response = await fetch(TOKEN_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: REFRESH_TOKEN,
      client_id: CLIENT_ID
    })
  });

  const data = await response.json();

  if (!response.ok) {
    throw new Error(
      `Spotify token refresh failed: ${
        data.error || response.status
      } ${data.error_description || ""}`.trim()
    );
  }

  return data.access_token;
}

async function spotifyRequest(token, endpoint, options = {}) {
  const response = await fetch(`${API}${endpoint}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      ...(options.headers || {})
    }
  });

  const text = await response.text();

  let data = {};

  try {
    data = text ? JSON.parse(text) : {};
  } catch {
    data = {};
  }

  if (!response.ok) {
    const retryAfter = response.headers.get("retry-after");

    throw new Error(
      `Spotify API ${response.status}: ${
        data.error?.message || text || "request failed"
      }${retryAfter ? ` (Retry-After: ${retryAfter}s)` : ""}`
    );
  }

  return data;
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function normalizeTrackIds(value, season) {
  if (!Array.isArray(value)) {
    throw new Error(
      `spotify-current.json is missing a valid array for "${season}".`
    );
  }

  const ids = [
    ...new Set(
      value
        .filter(Boolean)
        .map(String)
    )
  ];

  const invalid = ids.filter(
    id => !/^[A-Za-z0-9]{22}$/.test(id)
  );

  if (invalid.length) {
    throw new Error(
      `Invalid Spotify track ID(s) for "${season}": ${invalid.join(", ")}`
    );
  }

  return ids;
}

/*
 * Replace the entire Spotify playlist with the current RSS tracks.
 *
 * Spotify allows a maximum of 100 items per PUT request.
 *
 * The first PUT completely replaces the playlist.
 * Additional POST requests append the remaining tracks when a playlist
 * has more than 100 current tracks.
 */
async function replacePlaylistItems(
  token,
  playlistId,
  trackIds
) {
  const uris = trackIds.map(
    id => `spotify:track:${id}`
  );

  /*
   * First request:
   *
   * REPLACES EVERYTHING currently in the playlist.
   *
   * If trackIds is [] this clears the playlist completely.
   */
  const firstBatch = uris.slice(0, 100);

  await spotifyRequest(
    token,
    `/playlists/${playlistId}/items`,
    {
      method: "PUT",
      body: JSON.stringify({
        uris: firstBatch
      })
    }
  );

  /*
   * Append any remaining current-RSS tracks.
   */
  for (let i = 100; i < uris.length; i += 100) {
    const batch = uris.slice(i, i + 100);

    await spotifyRequest(
      token,
      `/playlists/${playlistId}/items`,
      {
        method: "POST",
        body: JSON.stringify({
          uris: batch
        })
      }
    );

    if (i + 100 < uris.length) {
      await sleep(500);
    }
  }
}

/*
 * spotify-current.json is generated by scrape.mjs immediately before
 * spotify.mjs is called.
 *
 * IMPORTANT:
 *
 * We NEVER fall back to:
 *   state.json
 *   spotify-playlists.json trackIds
 *
 * Those are historical/bookkeeping data.
 */
const config = await readJson(
  CONFIG_PATH,
  null
);

const current = await readJson(
  CURRENT_PATH,
  null
);

if (
  !config ||
  typeof config !== "object" ||
  Array.isArray(config)
) {
  throw new Error(
    "spotify-playlists.json is invalid."
  );
}

if (
  !current ||
  typeof current !== "object" ||
  Array.isArray(current)
) {
  throw new Error(
    "spotify-current.json is missing or invalid. Spotify sync aborted."
  );
}

const configuredSeasons =
  Object.keys(config);

if (!configuredSeasons.length) {
  throw new Error(
    "spotify-playlists.json contains no seasons."
  );
}

/*
 * Safety check:
 *
 * Every configured playlist must have a corresponding current-RSS
 * array.
 *
 * This prevents an incomplete spotify-current.json from accidentally
 * clearing a playlist.
 */
for (const season of configuredSeasons) {
  if (
    !Object.prototype.hasOwnProperty.call(
      current,
      season
    )
  ) {
    throw new Error(
      `spotify-current.json does not contain the configured season "${season}". Spotify sync aborted.`
    );
  }

  if (!Array.isArray(current[season])) {
    throw new Error(
      `spotify-current.json contains an invalid value for "${season}". Spotify sync aborted.`
    );
  }
}

const accessToken =
  await refreshAccessToken();

let totalCreated = 0;
let totalSynced = 0;
let totalCurrentTracks = 0;
let configChanged = false;

for (
  const [season, originalEntry]
  of Object.entries(config)
) {
  const entry =
    originalEntry &&
    typeof originalEntry === "object"
      ? originalEntry
      : {};

  /*
   * EXACT CURRENT RSS SPOTIFY TRACKS.
   *
   * This comes only from:
   *
   * scrape.mjs
   *      ↓
   * spotify-current.json
   */
  const desiredTracks =
    normalizeTrackIds(
      current[season],
      season
    );

  /*
   * Create playlist when necessary.
   */
  if (!entry.id) {
    console.log(
      `Creating Spotify playlist: ${season}`
    );

    const playlist =
      await spotifyRequest(
        accessToken,
        "/me/playlists",
        {
          method: "POST",
          body: JSON.stringify({
            name:
              `AniPlaylist — ${season}`,
            description:
              `Automatically updated from AniPlaylist RSS. Source: https://aniplaylist.com/?seasons=${encodeURIComponent(
                season
              )}`,
            public: true,
            collaborative: false
          })
        }
      );

    entry.id = playlist.id;

    entry.url =
      playlist.external_urls?.spotify ||
      `https://open.spotify.com/playlist/${playlist.id}`;

    totalCreated++;

    configChanged = true;

    console.log(
      `Created: ${entry.url}`
    );
  }

  console.log("");
  console.log(`=== ${season} ===`);

  console.log(
    `Current RSS Spotify tracks: ${desiredTracks.length}`
  );

  /*
   * EXACT REPLACEMENT
   *
   * Whatever is currently in Spotify is discarded.
   *
   * The playlist becomes exactly the current RSS Spotify list.
   */
  console.log(
    "Replacing Spotify playlist contents with current RSS tracks..."
  );

  await replacePlaylistItems(
    accessToken,
    entry.id,
    desiredTracks
  );

  /*
   * Update local bookkeeping.
   *
   * This does NOT determine what Spotify should contain.
   */
  const oldTrackIds =
    Array.isArray(entry.trackIds)
      ? entry.trackIds
      : [];

  if (
    JSON.stringify(oldTrackIds) !==
    JSON.stringify(desiredTracks)
  ) {
    configChanged = true;
  }

  entry.trackIds =
    desiredTracks;

  config[season] = entry;

  totalSynced++;
  totalCurrentTracks +=
    desiredTracks.length;

  console.log(
    `Playlist synchronized exactly: ${desiredTracks.length} track(s).`
  );
}

if (configChanged) {
  await fs.writeFile(
    CONFIG_PATH,
    JSON.stringify(
      config,
      null,
      2
    ) + "\n"
  );
}

console.log("");
console.log(
  "===== SPOTIFY SYNC ====="
);

console.log(
  `Playlists created: ${totalCreated}`
);

console.log(
  `Playlists synchronized: ${totalSynced}`
);

console.log(
  `Current RSS Spotify tracks: ${totalCurrentTracks}`
);

console.log(
  "Every Spotify playlist is now an exact mirror of spotify-current.json."
);

console.log(
  "========================"
);
