import fs from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();

const CONFIG_PATH = path.join(ROOT, "spotify-playlists.json");
const STATE_PATH = path.join(ROOT, "state.json");

const CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const REFRESH_TOKEN = process.env.SPOTIFY_REFRESH_TOKEN;

if (!CLIENT_ID || !REFRESH_TOKEN) {
  console.log("Spotify secrets are not configured; skipping Spotify playlist sync.");
  process.exit(0);
}

const API = "https://api.spotify.com/v1";
const TOKEN_URL = "https://accounts.spotify.com/api/token";

async function readJson(file, fallback) {
  try {
    return JSON.parse(await fs.readFile(file, "utf8"));
  } catch {
    return fallback;
  }
}

async function refreshAccessToken() {
  const response = await fetch(TOKEN_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: REFRESH_TOKEN,
      client_id: CLIENT_ID
    })
  });

  const data = await response.json();

  if (!response.ok) {
    throw new Error(
      `Spotify token refresh failed: ${
        data.error || response.status
      } ${data.error_description || ""}`.trim()
    );
  }

  return data.access_token;
}

async function spotifyRequest(token, endpoint, options = {}) {
  const response = await fetch(`${API}${endpoint}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      ...(options.headers || {})
    }
  });

  const text = await response.text();

  let data = {};

  try {
    data = text ? JSON.parse(text) : {};
  } catch {
    data = {};
  }

  if (!response.ok) {
    const retryAfter = response.headers.get("retry-after");

    const retryText = retryAfter
      ? ` (Retry-After: ${retryAfter}s)`
      : "";

    throw new Error(
      `Spotify API ${response.status}: ${
        data.error?.message || text || "request failed"
      }${retryText}`
    );
  }

  return data;
}

function spotifyTrackId(url) {
  const match = String(url || "").match(
    /https?:\/\/open\.spotify\.com\/track\/([A-Za-z0-9]+)/i
  );

  return match?.[1] || "";
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const config = await readJson(CONFIG_PATH, {});
const state = await readJson(STATE_PATH, {});

const accessToken = await refreshAccessToken();

/*
 * Build:
 *
 * season -> Set of Spotify track IDs
 *
 * state.json is generated by scrape.mjs and contains the
 * Spotify URL discovered for each AniPlaylist entry.
 */
const discovered = {};

for (const value of Object.values(state)) {
  if (!value || !value.season || !value.spotify) {
    continue;
  }

  const trackId = spotifyTrackId(value.spotify);

  if (!trackId) {
    continue;
  }

  if (!discovered[value.season]) {
    discovered[value.season] = new Set();
  }

  discovered[value.season].add(trackId);
}

let totalCreated = 0;
let totalAdded = 0;
let configChanged = false;

for (const [season, originalEntry] of Object.entries(config)) {
  const entry =
    originalEntry && typeof originalEntry === "object"
      ? originalEntry
      : {};

  entry.trackIds = Array.isArray(entry.trackIds)
    ? [...new Set(entry.trackIds.filter(Boolean))]
    : [];

  /*
   * Create the playlist automatically if it doesn't exist yet.
   */
  if (!entry.id) {
    console.log(`Creating Spotify playlist: ${season}`);

    const playlist = await spotifyRequest(
      accessToken,
      "/me/playlists",
      {
        method: "POST",
        body: JSON.stringify({
          name: `AniPlaylist — ${season}`,
          description:
            `Automatically updated from AniPlaylist RSS. ` +
            `Source: https://aniplaylist.com/?seasons=${encodeURIComponent(
              season
            )}`,
          public: true,
          collaborative: false
        })
      }
    );

    entry.id = playlist.id;

    entry.url =
      playlist.external_urls?.spotify ||
      `https://open.spotify.com/playlist/${playlist.id}`;

    totalCreated++;
    configChanged = true;

    console.log(`Created: ${entry.url}`);
  }

  const known = new Set(entry.trackIds);

  const seasonTracks = [
    ...(discovered[season] || new Set())
  ];

  const newTracks = seasonTracks.filter(
    trackId => !known.has(trackId)
  );

  if (newTracks.length === 0) {
    console.log(`${season}: no new Spotify tracks.`);
    config[season] = entry;
    continue;
  }

  /*
   * Spotify allows multiple items in one request.
   * Keep batches at 100.
   */
  for (let i = 0; i < newTracks.length; i += 100) {
    const batch = newTracks.slice(i, i + 100);

    console.log(
      `${season}: adding ${batch.length} new track(s)...`
    );

    await spotifyRequest(
      accessToken,
      `/playlists/${entry.id}/items`,
      {
        method: "POST",
        body: JSON.stringify({
          uris: batch.map(
            id => `spotify:track:${id}`
          )
        })
      }
    );

    for (const trackId of batch) {
      entry.trackIds.push(trackId);
    }

    totalAdded += batch.length;
    configChanged = true;

    /*
     * Small delay between batches.
     */
    if (i + 100 < newTracks.length) {
      await sleep(500);
    }
  }

  entry.trackIds = [
    ...new Set(entry.trackIds)
  ];

  config[season] = entry;
}

if (configChanged) {
  await fs.writeFile(
    CONFIG_PATH,
    JSON.stringify(config, null, 2) + "\n"
  );
}

console.log("");
console.log("===== SPOTIFY SYNC =====");
console.log(`Playlists created: ${totalCreated}`);
console.log(`Tracks added:      ${totalAdded}`);
console.log("========================");
