import fs from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();

const CONFIG_PATH = path.join(ROOT, "spotify-playlists.json");
const CURRENT_PATH = path.join(ROOT, "spotify-current.json");

const CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const REFRESH_TOKEN = process.env.SPOTIFY_REFRESH_TOKEN;

if (!CLIENT_ID || !REFRESH_TOKEN) {
  console.log(
    "Spotify secrets are not configured; skipping Spotify playlist sync."
  );
  process.exit(0);
}

const API = "https://api.spotify.com/v1";
const TOKEN_URL = "https://accounts.spotify.com/api/token";

async function readJson(file, fallback) {
  try {
    return JSON.parse(await fs.readFile(file, "utf8"));
  } catch {
    return fallback;
  }
}

async function refreshAccessToken() {
  const response = await fetch(TOKEN_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded"
    },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: REFRESH_TOKEN,
      client_id: CLIENT_ID
    })
  });

  const data = await response.json();

  if (!response.ok) {
    throw new Error(
      `Spotify token refresh failed: ${
        data.error || response.status
      } ${data.error_description || ""}`.trim()
    );
  }

  return data.access_token;
}

async function spotifyRequest(token, endpoint, options = {}) {
  const response = await fetch(`${API}${endpoint}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      ...(options.headers || {})
    }
  });

  const text = await response.text();

  let data = {};

  try {
    data = text ? JSON.parse(text) : {};
  } catch {
    data = {};
  }

  if (!response.ok) {
    const retryAfter = response.headers.get("retry-after");

    throw new Error(
      `Spotify API ${response.status}: ${
        data.error?.message || text || "request failed"
      }${retryAfter ? ` (Retry-After: ${retryAfter}s)` : ""}`
    );
  }

  return data;
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

/*
 * spotify-current.json is generated by scrape.mjs.
 *
 * IMPORTANT:
 * This file contains ONLY Spotify tracks found during the
 * CURRENT AniPlaylist scrape.
 *
 * We deliberately do NOT use state.json here.
 */
const config = await readJson(CONFIG_PATH, {});
const current = await readJson(CURRENT_PATH, {});

const accessToken = await refreshAccessToken();

let totalCreated = 0;
let totalAdded = 0;
let totalRemoved = 0;
let configChanged = false;

for (const [season, originalEntry] of Object.entries(config)) {
  const entry =
    originalEntry && typeof originalEntry === "object"
      ? originalEntry
      : {};

  entry.trackIds = Array.isArray(entry.trackIds)
    ? [...new Set(entry.trackIds.filter(Boolean))]
    : [];

  /*
   * EXACT CURRENT RSS TRACKS
   */
  const desiredTracks = [
    ...new Set(
      Array.isArray(current[season])
        ? current[season].filter(Boolean)
        : []
    )
  ];

  /*
   * Create playlist automatically if necessary.
   */
  if (!entry.id) {
    console.log(`Creating Spotify playlist: ${season}`);

    const playlist = await spotifyRequest(
      accessToken,
      "/me/playlists",
      {
        method: "POST",
        body: JSON.stringify({
          name: `AniPlaylist — ${season}`,
          description:
            `Automatically updated from AniPlaylist RSS. ` +
            `Source: https://aniplaylist.com/?seasons=${encodeURIComponent(
              season
            )}`,
          public: true,
          collaborative: false
        })
      }
    );

    entry.id = playlist.id;

    entry.url =
      playlist.external_urls?.spotify ||
      `https://open.spotify.com/playlist/${playlist.id}`;

    totalCreated++;
    configChanged = true;

    console.log(`Created: ${entry.url}`);
  }

  /*
   * Read the ACTUAL Spotify playlist.
   *
   * This prevents our local historical state from being treated
   * as the source of truth.
   */
  const actualIds = new Set();
  const actualItems = [];

  let offset = 0;

  while (true) {
    const data = await spotifyRequest(
      accessToken,
      `/playlists/${entry.id}/items?limit=50&offset=${offset}`,
      {
        method: "GET"
      }
    );

    const items = Array.isArray(data.items)
      ? data.items
      : [];

    for (const item of items) {
      const track = item?.item;

      if (!track || track.type !== "track") {
        continue;
      }

      const id = track.id;

      if (!id) {
        continue;
      }

      actualIds.add(id);

      actualItems.push({
        id,
        uri: track.uri,
        addedAt: item.added_at || null
      });
    }

    if (
      items.length === 0 ||
      actualItems.length >= Number(data.total || 0)
    ) {
      break;
    }

    offset += items.length;
  }

  console.log("");
  console.log(`=== ${season} ===`);
  console.log(`RSS tracks:      ${desiredTracks.length}`);
  console.log(`Spotify tracks:  ${actualIds.size}`);

  /*
   * ============================================================
   * REMOVE TRACKS THAT ARE NOT IN THE CURRENT RSS
   * ============================================================
   *
   * This is the important cleanup.
   *
   * Example:
   *
   * RSS Winter 2027:
   *   A
   *   B
   *
   * Spotify Winter 2027:
   *   A
   *   B
   *   2vB0EKXrPcYIshTXZFtQVP
   *
   * The old 2025 track gets removed.
   */
  const obsolete = actualItems.filter(
    item => !desiredTracks.includes(item.id)
  );

  /*
   * Remove in batches of 100.
   */
  for (let i = 0; i < obsolete.length; i += 100) {
    const batch = obsolete.slice(i, i + 100);

    console.log(
      `${season}: removing ${batch.length} track(s) not present in current RSS...`
    );

    await spotifyRequest(
      accessToken,
      `/playlists/${entry.id}/items`,
      {
        method: "DELETE",
        body: JSON.stringify({
          items: batch.map(item => ({
            uri: item.uri
          }))
        })
      }
    );

    totalRemoved += batch.length;

    if (i + 100 < obsolete.length) {
      await sleep(500);
    }
  }

  /*
   * ============================================================
   * ADD ONLY CURRENT RSS TRACKS
   * ============================================================
   */
  const missing = desiredTracks.filter(
    id => !actualIds.has(id)
  );

  for (let i = 0; i < missing.length; i += 100) {
    const batch = missing.slice(i, i + 100);

    console.log(
      `${season}: adding ${batch.length} new RSS track(s)...`
    );

    await spotifyRequest(
      accessToken,
      `/playlists/${entry.id}/items`,
      {
        method: "POST",
        body: JSON.stringify({
          uris: batch.map(
            id => `spotify:track:${id}`
          )
        })
      }
    );

    totalAdded += batch.length;

    if (i + 100 < missing.length) {
      await sleep(500);
    }
  }

  /*
   * Local config is now just a record of the current desired
   * Spotify IDs, NOT the source of truth.
   */
  const newTrackIds = [...desiredTracks];

  if (
    JSON.stringify(entry.trackIds) !==
    JSON.stringify(newTrackIds)
  ) {
    entry.trackIds = newTrackIds;
    configChanged = true;
  }

  config[season] = entry;

  console.log(`Added:            ${missing.length}`);
  console.log(`Removed:          ${obsolete.length}`);
}

if (configChanged) {
  await fs.writeFile(
    CONFIG_PATH,
    JSON.stringify(config, null, 2) + "\n"
  );
}

console.log("");
console.log("===== SPOTIFY SYNC =====");
console.log(`Playlists created: ${totalCreated}`);
console.log(`Tracks added:      ${totalAdded}`);
console.log(`Tracks removed:    ${totalRemoved}`);
console.log("========================");
